import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import api from "../api";

const Poster = () => {
  const { id } = useParams();
  const [item, setItem] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchItem = async () => {
      try {
        const res = await api.get(`/items/${id}`);
        setItem(res.data);
      } catch (err) {
        console.error("Poster Error:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchItem();
  }, [id]);

  useEffect(() => {
    // Auto-trigger print when item is loaded and mostly rendered
    if (item) {
      // Wait a bit for images to render before launching print dialog
      // This prevents "blank image" issues in the print preview
      setTimeout(() => {
        window.print();
      }, 1500);
    }
  }, [item]);

  if (loading) return <div className="p-10 text-center">Loading Poster...</div>;
  if (!item) return <div className="p-10 text-center">Item Not Found</div>;

  const isLost = item.type === "lost";
  const primaryColor = isLost ? "#dc2626" : "#16a34a"; // Red vs Green
  const bgGradient = isLost
    ? "linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)"
    : "linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)";
  const borderColor = isLost ? "#ef4444" : "#22c55e";

  // Use the Item URL for the QR Code
  // window.location.origin gives us the current frontend domain (e.g., https://my-app.vercel.app)
  const itemUrl = `${window.location.origin}/item/${item.id}`;
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=${itemUrl}`;

  // Date formatting
  const dateStr = item.date_lost
    ? new Date(item.date_lost).toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
      })
    : "Unknown Date";

  return (
    <div className="poster-body">
      <div className="page-bg">
        <div className="card">
          <div className="header">
            <h1 className="header-title">{item.type}</h1>
            <div className="sub-title">{item.description}</div>
          </div>

          <div className="content">
            <div className="main-image-container">
              {item.image_url ? (
                <img
                  src={item.image_url}
                  className="main-image"
                  alt="Lost Item"
                  onError={(e) => {
                    e.target.onerror = null;
                    e.target.src =
                      "https://placehold.co/600x400?text=Image+Not+Found";
                  }}
                />
              ) : (
                <img
                  src="https://placehold.co/600x400?text=No+Image+Available"
                  className="main-image"
                />
              )}
            </div>

            <div className="info-grid">
              <div className="info-box">
                <div className="label">Date Missing/Found</div>
                <div className="value">{dateStr}</div>
              </div>
              <div className="info-box">
                <div className="label">Location</div>
                <div className="value">{item.location}</div>
              </div>
              <div className="info-box">
                <div className="label">Item Category</div>
                <div className="value">{item.category || "General"}</div>
              </div>
              <div className="info-box">
                <div className="label">Color / Brand</div>
                <div className="value">
                  {item.color || "-"} / {item.brand || "-"}
                </div>
              </div>
            </div>

            <div className="bottom-section">
              <img src={qrUrl} className="qr-code" alt="QR Code" />
              <div className="cta">
                <h3>HELP RETURN THIS!</h3>
                <p>
                  Scan the code to contact the owner or claim this item securely
                  via CampusFind.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="footer-text">Generated by CampusFind</div>
      </div>

      {/* Embedded CSS for Poster Styling */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Anton&family=Inter:wght@400;600;800&display=swap');
  
        .poster-body {
            font-family: 'Inter', sans-serif;
            margin: 0;
            padding: 0;
            color: #1f2937;
            background: white;
            -webkit-print-color-adjust: exact;
            min-height: 100vh;
        }

        .page-bg {
            width: 100%;
            min-height: 100vh;
            background: ${bgGradient};
            padding: 40px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .card {
            background: white;
            border: 8px solid ${borderColor};
            border-radius: 30px;
            width: 100%;
            max-width: 800px;
            overflow: hidden;
            box-shadow: 0 20px 50px rgba(0,0,0,0.15);
        }

        .header {
            background: ${primaryColor};
            color: white;
            padding: 20px;
            text-align: center;
        }

        .header-title {
            font-family: 'Anton', sans-serif;
            font-size: 8rem;
            line-height: 0.9;
            text-transform: uppercase;
            letter-spacing: 2px;
            margin: 0;
        }

        .sub-title {
            font-size: 2rem;
            font-weight: 800;
            margin-top: 10px;
            text-transform: uppercase;
            opacity: 0.9;
        }

        .content { padding: 30px; }

        .main-image-container {
            width: 100%;
            height: 500px;
            background: #000;
            border-radius: 15px;
            overflow: hidden;
            margin-bottom: 30px;
            display: flex;
            align-items: center;
            justify-content: center;
            border: 2px solid #ddd;
        }

        .main-image {
            width: 100%;
            height: 100%;
            object-fit: contain;
            background: white;
        }

        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 30px;
        }

        .info-box {
            background: #f9fafb;
            padding: 15px;
            border-radius: 12px;
            border-left: 5px solid ${borderColor};
        }

        .label {
            font-size: 0.9rem;
            text-transform: uppercase;
            color: #6b7280;
            font-weight: 700;
            margin-bottom: 5px;
        }

        .value {
            font-size: 1.4rem;
            font-weight: 700;
        }

        .bottom-section {
            background: #f3f4f6;
            border-radius: 20px;
            padding: 20px;
            display: flex;
            align-items: center;
            gap: 20px;
            border: 2px dashed #9ca3af;
        }

        .qr-code { width: 150px; height: 150px; mix-blend-mode: multiply; }

        .cta { flex: 1; text-align: left; }
        .cta h3 { font-size: 2rem; font-weight: 900; margin: 0 0 5px 0; line-height: 1; }
        .cta p { font-size: 1.1rem; margin: 0; color: #4b5563; }
        
        .footer-text {
            margin-top: 20px;
            font-size: 12px; 
            opacity: 0.7;
        }

        @media print {
            @page { margin: 0.25in; size: portrait; } /* Force Portrait */
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            
            .poster-body { 
                height: auto;
                width: 100%;
                display: block; /* Remove flex to fix weird centering/squishing */
            }

            .page-bg { 
                min-height: 100%; 
                padding: 0;
            }

            .card { 
                box-shadow: none; 
                border-width: 4px;
                /* No scale needed if layout is simple */
                max-width: 100%;
                width: 100%;
                margin: 0 auto;
            }
        }
      `}</style>
    </div>
  );
};

export default Poster;
