from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=True) # Optional for now
    password_hash = db.Column(db.String(200), nullable=True) # Nullable for Google Auth users
    google_id = db.Column(db.String(200), unique=True, nullable=True)
    role = db.Column(db.String(20), default='student') # student, admin
    
    items = db.relationship('Item', backref='user', lazy=True)
    claims = db.relationship('Claim', backref='claimant', lazy=True)
    
    # Profile Extensions
    phone = db.Column(db.String(20), nullable=True)
    bio = db.Column(db.Text, nullable=True)
    profile_photo = db.Column(db.String(500), nullable=True)
    read_notifications = db.Column(db.Text, default='[]') # JSON list of read notification IDs
    fcm_token = db.Column(db.Text, nullable=True) # Firebase Cloud Messaging Token
    
    # Gamification
    trust_score = db.Column(db.Integer, default=0) # +10 for returning item, etc.

class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    type = db.Column(db.String(20), nullable=False) # 'lost' or 'found'
    description = db.Column(db.Text, nullable=False)
    location = db.Column(db.String(200), nullable=False)
    date_lost = db.Column(db.DateTime, default=datetime.utcnow)
    image_url = db.Column(db.String(500), nullable=True) # Legacy/Backup
    image_data = db.Column(db.Text, nullable=True) # Base64 Data URI (Vercel persistence)
    status = db.Column(db.String(20), default='unresolved') # unresolved, matched, claimed
    
    # Founder contact info (if type='found')
    finder_name = db.Column(db.String(100), nullable=True)
    finder_phone = db.Column(db.String(20), nullable=True)
    contact_info = db.Column(db.String(200), nullable=True) # Phone/Socials for contact
    is_with_finder = db.Column(db.Boolean, default=True) # True if with finder, False if submitted somewhere
    
    # AI Tags
    category = db.Column(db.String(50), nullable=True)
    color = db.Column(db.String(50), nullable=True)
    brand = db.Column(db.String(50), nullable=True)
    distinctive_features = db.Column(db.Text, nullable=True) # JSON string of unique features

    # Verification Question (generated by AI for Found items)
    verification_question = db.Column(db.String(500), nullable=True)
    verification_answer = db.Column(db.String(500), nullable=True) # The 'correct' answer derived by AI/User
    verification_answer_type = db.Column(db.String(50), nullable=True) # Type of answer expected

    # Relationships
    claims = db.relationship('Claim', backref='item', lazy=True)

class Claim(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    item_id = db.Column(db.Integer, db.ForeignKey('item.id'), nullable=False)
    claimant_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    
    # Claim Details
    message = db.Column(db.Text, nullable=True) # Message from claimant
    proof_image = db.Column(db.String(500), nullable=True) # Optional proof
    proof_image_data = db.Column(db.Text, nullable=True) # Base64 Data URI (Vercel persistence)
    
    # Status
    status = db.Column(db.String(20), default='pending') # pending, accepted, rejected, handed_over
    response_message = db.Column(db.Text, nullable=True) # Message from founder
    
    # Meeting Details (set by founder upon acceptance)
    meeting_location = db.Column(db.String(200), nullable=True)
    meeting_time = db.Column(db.DateTime, nullable=True)
    
    # Verification
    qr_code = db.Column(db.String(500), nullable=True) # Unique string/token for QR
    
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
